# Generated by Django 2.2.4 on 2019-08-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscription_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='post',
        ),
    ]
